apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - project.senticor.runs.onstackit.cloud
      secretName: project-tls
  rules:
    - host: project.senticor.runs.onstackit.cloud
      http:
        paths:
          - path: /storybook
            pathType: Prefix
            backend:
              service:
                name: storybook
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
