apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Cs+Ch2Kzbr791D35nnwJdKesNzatBhE=,iv:KDZi+GL5EH0C5bs8Zg1dW8repcHsbCYlhIUHsgWaYOU=,tag:msspbiZvqZ+9KPrIBXG+Dw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:9gsvh9Z0bvQHa2J1ei2oBwO/p8WA6af3pTZt3yx4163x83k3USsUZgSztA==,iv:kxfcPO8XnpQ3E06kcUd6l17gQTqNcln95cgqZl2wWBw=,tag:uXP0aZ7HpiVLfpDbIABH/g==,type:str]
    GMAIL_CLIENT_ID: ENC[AES256_GCM,data:SldZ5cYG1xDwBIQcPa+v9CfcNw0xV27EkjYdDIg1hvZhCBnMFVnQ6l0uhKzc6BzZ4dU5L1a4V0IoIY8G8FlzI+O2hvuz5c1t,iv:lYbgBLmon+SIqmN2ieBocg3M6QHMwVGfzUQjEtr33JA=,tag:NZEbD3o1eHK406iSpo2V9g==,type:str]
    GMAIL_CLIENT_SECRET: ENC[AES256_GCM,data:TzEVkwI9Y8N4ypx9Albc7sEtpDsKs4MZZhyQ96j8d7/ycPs=,iv:uix+9Iu9IVg+xRAjHSbhOCXHXmOXbGilfOTdkvH0Trs=,tag:gEGSBNSCD2gMSK5BNOTvug==,type:str]
    GMAIL_STATE_SECRET: ENC[AES256_GCM,data:2TrG8JiEFq5BXh47gJ+8XqT/lorsc7/EkrYNAzkzuZzlPHmY7pLViZklXA==,iv:8heADHzS7CqO3oOITLZL0lu309YC3JhiliipXoq/two=,tag:0NpmwiN34PSyMioQDe7K8A==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:/cUys3w2NZe8wAN+Ozq+rKN4BLYvWO1V1MXWs+LthQPssM1ecvOoMqp6iEs=,iv:sJqeEbPFC87sz1qZpg7j4iUgCWNwWXBFei8GXmLTiJE=,tag:QNZQfGEVkI4vB+54Fsv/7A==,type:str]
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:+An6CgOE3JoDfj2zrpZFvXRgwRZhnzbKOicIvcG7NsEi/McmUUbCjzvi7D4Fusv80NYvsSujGn2hjtdtztDANwNzpqU1eLLj9bSIh0gsnZIq5VpP91kR,iv:uueMUo87WKQMAv2gITpLptzQ7F2AQetu2ZqIkezX20A=,tag:KlsxBZgDt6QaDm8zqSw1sg==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:ln9dezXiasidBCMSAxPSXi8BSmFlSdb6PAlqiHiza0kkE4PC/bDwQt8oTg==,iv:LOfVMVMRutgVKyvHrUlHSq/YMCEb5P4s4gt+WjyGHhk=,tag:wGTbJT7svaOf8XC6EF2RuQ==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:OPx2SkYknUEGxJVT47EOpg0v2qzWGliCBq+fq2+k1gEptJRW3JMNmkMH7W5uy0IXVaDeV/r4+cmxNB+2T2RymmcobyKuLbqzqQ==,iv:eJpvdgBcVarssS9KndAn0Emyx1NVb3aD49EzHDkJPj4=,tag:aRM8AU7qt0Z3UdpVFYP8ig==,type:str]
sops:
    age:
        - recipient: age196lkud7akr9e3npwcwf667mxs0nqzcy63hp9f5q2aqcyjwnhqqxqp36s8j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQV1ljK2FabENhbEtSZW9u
            cTVDNG9GTldSalpuU08velhwcHM2OWFwbUU0ClR3RDhJbTZVUko5dW5TRUFWN0R4
            a2ZwQVhrMDdqcEVtdVlqSzhnQXVhd1UKLS0tIFM5RUFObmRDK2lyOTh3Z2gzQlUr
            b25aTDYxRHNLM2NaUmJKb1VsR2lDVncKGFnR7KGRlVlTXRdXaH4SybRUH9u8qbQ/
            nHTWR2eFrf96wnnMve8vXp1R879NUFBA5v61fxF1LTYU0Xi6rd9f5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-12T15:36:14Z"
    mac: ENC[AES256_GCM,data:6JWT5suOIZBM8J51XB0BSa/PnbUKj5C+tI87q7AWm6befwoCe+Rc/PTJ9MWFqWnFFmGXdLK3Memv/IJljrjCPeOARQbDeOD6bHzBj6e3YMc4ZdatYla/vKG0Dz2QXekgf9ReLERJjCqnJvcTmj1ls4j6OlkuSiI/zYEHjDAFlE0=,iv:5wA/6ejG7eEutNwrBmJfKq6iYw36iqy3UpCR1YLNFiM=,tag:Or554eVuIpvXeCUMcRUwJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
