apiVersion: apps/v1
kind: Deployment
metadata:
  name: watch-worker
spec:
  template:
    spec:
      containers:
        - name: watch-worker
          volumeMounts:
            - name: pubsub-sa
              mountPath: /etc/gcp
              readOnly: true
      volumes:
        - name: pubsub-sa
          secret:
            secretName: pubsub-sa
