apiVersion: v1
kind: ConfigMap
metadata:
  name: gitlab-ci-exporter-config
data:
  config.yaml: |
    gitlab:
      url: https://gitlab.100-114-108-51.nip.io:30443
      health_url: https://gitlab.100-114-108-51.nip.io:30443/-/health
    projects:
      - name: wolfgangihloff/terminandoyo
        pull:
          refs:
            regexp: "^main$"
          pipeline:
            jobs:
              enabled: true
    server:
      metrics:
        enabled: true
      listen_address: ":8080"
