apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: terminandoyo
resources:
  - ../../base
  - namespace.yaml
  - configmap.yaml
  - gitlab-ci-exporter-config.yaml
  - secret.yaml
  - ingress.yaml

patches:
  - path: patch-watch-worker-disabled.yaml
