apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc-backend-files.yaml
  - postgres.yaml
  - backend.yaml
  - worker.yaml
  - push-worker.yaml
  - watch-worker.yaml
  - frontend.yaml
  - storybook.yaml
